# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 120,
      y: 49,
      yaw: 90},
    "1":{
      x: 120,
      y: 49,
      yaw: 90},
    "2":{
      x: 122,
      y: 49,
      yaw: 90},
    "3":{
      x: 124,
      y: 49,
      yaw: 90},
    "4":{
      x: 126,
      y: 49,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 218,
      y: 491,
      yaw: 270},
    "6":{
      x: 220,
      y: 491,
      yaw: 270},
    "7":{
      x: 222,
      y: 491,
      yaw: 270},
    "8":{
      x: 224,
      y: 491,
      yaw: 270},
    "9":{
      x: 226,
      y: 491,
      yaw: 270},
  },
}
