game_master_node:
  ros__parameters:
    use_sim_time: True
    drone_detection_range: 20.0
    ship_detection_range: 20.0
    drone_communication_range: 15.0
    ship_communication_range: 30.0
    drone_health: 10
    ship_health: 20
    drone_points: 10
    ship_points: 50
    game_duration: 200  # 5 minutes
    world_name: "swarmz_world_2"

missile_server:
  ros__parameters:
    use_sim_time: True
    drone_missile_range: 100.0
    ship_missile_range: 200.0
    drone_missile_damage: 10
    ship_missile_damage: 20
    drone_cooldown: 1.0
    ship_cooldown: 2.0
    drone_magazine: 5
    ship_magazine: 10
    laser_width: 3.0
    drone_padding_x: 0.5
    drone_padding_y: 0.5
    drone_padding_z: 0.5
    ship_padding_x: 6.0
    ship_padding_y: 1.0
    ship_padding_z: 1.0
    world_name: "swarmz_world_2"

kamikaze_server:
  ros__parameters:
    use_sim_time: True
    explosion_damage: 100.0
    explosion_range: 6.0
    world_name: "swarmz_world_2"